--- 
javascripts: 
- base: 
  - jquery-ui-1.8.2.custom/js/jquery-1.4.2.min
  - jquery-ui-1.8.2.custom/js/jquery-ui-1.8.2.custom.min
  - jquery.livequery
  - jquery.wresize
  - jquery.jeditable
  - jquery.editinplace
  - jquery.form
  - jquery.colorbox
  - JSLINQ/IEnumerable
  - JSLINQ/JSLINQ
  - application
  - radtrack.livesearch
  - routes
- tail:
  - project
  - user
  - kanban_card
  - card_owner
  - kanban
  - backlog
  - card
  - colorbox_card
  - team_members
  - user_tabs
stylesheets: 
- base: 
  - application
  - projects
  - yui
  - default
  - buttons
  - colorbox_card
  - ../javascripts/jquery-ui-1.8.2.custom/css/ui-lightness/jquery-ui-1.8.2.custom.css
